### PR TITLE
Improved docs

### PR DESCRIPTION
**Pull request by LorenzoScebba**
There was way too much english, Adës l'è tüt bèl e tröt in bergamasch.

### CODE REVIEW

**Comment by McMatthew** [comment]
lgtm... lgbt

**Comment by christian-desimone-deltatre** [comment]
lgtm

**Comment by Silvio-il-Berlu** [comment]
lgtm, mi consenta

**Comment by fabio-grieco** [comment]
a mé al somèa bü

**Comment by a-cinchetti** [comment]
lgtm

**Comment by SimoRec** [comment]
lgtm

**Comment by MBonini** [comment]
lgtm

**Review by PiDayDev — APPROVED** [review]

**Pull request merged**
